{% set name = "cbor2" %}
{% set version = "5.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cbor2-{{ version }}.tar.gz
  sha256: 3f6d843f4db4d0ec501c46453c22a4fbebb1abfb5b740e1bcab34c615cd7406b

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  entry_points:
    - cbor2=cbor2.tool:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools >=77
    - setuptools-scm >=6.4
    - tomli
    - pip
  run:
    - python

test:
  imports:
    - cbor2
  commands:
    - pip check
    - cbor2 --help
  requires:
    - pip

about:
  home: https://github.com/agronholm/cbor2
  doc_url: https://cbor2.readthedocs.io/
  summary: CBOR (de)serializer with extensive tag support
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
