{% set name = "cbor2" %}
{% set version = "5.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cbor2-{{ version }}.tar.gz
  sha256: b682820677ee1dbba45f7da11898d2720f92e06be36acec290867d5ebf3d7e09

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools >=61
    - setuptools-scm >=6.4
    - pip
  run:
    - python

test:
  imports:
    - cbor2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/agronholm/cbor2
  doc_url: https://cbor2.readthedocs.io/
  summary: CBOR (de)serializer with extensive tag support
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
